all:
javac com/CommonProperties.java
javac com/PeerInfo.java
javac com/PeerInfoProperties.java
javac connection/ConnectionHandler.java
javac files/FileManager.java
javac files/FileUtilities.java
javac log/WriteLog.java
javac messages/Handshake.java
javac messages/Message.java
javac messages/MessageType.java
javac payloads/BitField.java
javac payloads/Choke.java
javac payloads/Have.java
javac payloads/Interested.java
javac payloads/NotInterested.java
javac payloads/Payload.java
javac payloads/Piece.java
javac payloads/Request.java
javac payloads/Unchoke.java
javac peers/Peer.java
javac peers/PeerManager.java
javac peers/PeerProcess.java
javac peers/Process.java
javac peers/RemotePeerInfo.java
javac start/StartRemotePeers.java
javac util/Constants.java
javac Client.java
javac Server.java

clean:
$(RM) *.class

